### ISSUE TITLE
Error reporting is not very useful

### ISSUE THREAD

**Issue by alexflav23** [sbt/sbt-less#67]
Error propagation from the Less compiler seems to be unfortunately on the TODO list, at least in version `1.0.1`.

``` scala

[error] 
[error] /Users/flavian/projects/s/s/project/target/node-modules/webjars/less/lib/less/parser.js:604
[error]                         throw new(LessError)(e, env);
[error]                               ^
[error] Error
[error]     at new Parser (/Users/flavian/projects/s/s/project/target/node-modules/webjars/less/lib/less/parser.js:333:27)
[error]     at /Users/flavian/projects/s/s/project/target/less/sbt-less-1.0.1.jar:57:26
[error]     at fs.js:334:14
[error]     at FSReqWrap.oncomplete (fs.js:95:15)
[info] 
[trace] Stack trace suppressed: run last api/web-assets:less for the full output.
[error] (api/web-assets:less) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: 
[error] /Users/flavian/projects/s/s/project/target/node-modules/webjars/less/lib/less/parser.js:604
[error]                         throw new(LessError)(e, env);
[error]                               ^
[error] Error
[error]     at new Parser (/Users/flavian/projects/s/s/project/target/node-modules/webjars/less/lib/less/parser.js:333:27)
[error]     at /Users/flavian/projects/s/s/project/target/less/sbt-less-1.0.1.jar:57:26
[error]     at fs.js:334:14
[error]     at FSReqWrap.oncomplete (fs.js:95:15)

```

Even the full phase error display is just as useless, when triggered by: `last api/web-assets:less`. It would make sense to propagate the actual list of compiler errors to the SBT console and display all the errors as they are, as right now I have absolutely no idea what is going wrong and other than a lot of guess work not much can be done with the plugin itself.

Are there any existing plans to fix this?

**Comment by jroper** [comment]
I know this is an old issue, but error reporting is something that has always been supported, errors should be nicely rendered, including a snippet of source code and a caret pointing to the exact place of the error. We have tests that ensure this works here:

https://github.com/sbt/sbt-less/blob/master/src/sbt-test/sbt-less-plugin/error-output/test

So this is either a specific error that we're not catching for some reason, or a specific configuration that's breaking error reporting. Closing due to how old this issue is, but if you have a reproducer, feel free to reopen.
