### ISSUE TITLE
File compilation when included file change

### ISSUE THREAD

**Issue by KarelCemus** [sbt/sbt-less#72]
In our application, we have few (usually 2 or 3) main LESS files producing CSS for web pages. All other files (many) are included into one or more of these main files through `include` statement. However, when we update any of these helpers, main files are not automatically recompiled. It requires to manually change them every time we want them to be up-to-date. This is very inconvenient especially when we are fixing/updating web page design. 

Is there any way how to automatically recompile this main files (defined in `includeFilter`) when their dependencies change?

For easier testing [there is](https://github.com/KarelCemus/sbt-less-test) very simple application with one main file and one included file.

**Comment by janwillemvd** [comment]
Thanks for opening this issue. We've encountered exactly the same problem!

**Comment by damirv** [comment]
Same here. @jroper do you have any idea in which direction to look? I'd love to help but I'm not sure where to look for the problem.

**Comment by damirv** [comment]
I have more information about the issue: it seems that the imported file gets processed but the main file (the one that is importing it) does not. So for example, let's say you have the following:

`main.less`:
```
@import "test";

h1 {
  color: blue;
}
```

`test.less`:
```
h2 {
  color: green;
}
```

and with the following settings

```
    includeFilter in(Assets, LessKeys.less) := "*.less",

    excludeFilter in(Assets, LessKeys.less) := "_*.less",
```

If you change something in `test.less`, the `test.css` file will contain the up-to-date css but `main.css` will not (i.e., it has not run less on `main.less`).

**Comment by jroper** [comment]
What version of sbt-less are you using?

We certainly do have code that's supposed to handle tracking imports so we can know which files need recompilation, and I'm pretty sure at one stage this did work, but perhaps the upgrade to less 2.5 broke this.  We don't have any tests for it, so that should be fixed.

**Comment by jroper** [comment]
Attached PR to fix this.

**Comment by jroper** [comment]
I've just released sbt-less 1.1.1 with this fix.

**Comment by KarelCemus** [comment]
I confirm it is resolved. Thank you @jroper!

**Comment by janwillemvd** [comment]
Great @jroper. It works indeed like a charm!

**Comment by rethab** [comment]
@jroper could you please elaborate as to how your change fixes the issue?

For me, since this change was introduced, the compiler hangs with node. It seems to work with Trireme though.

**Comment by jroper** [comment]
The problem was that Play was treating the imports list as an object, not an array, so sbt-less was not correctly recording the dependencies of a file, which meant when the dependencies changed, the file was not recompiled.

**Comment by rethab** [comment]
Alright, thanks.

For the record, it hangs forever on our lower end machines (mac mini, mb air) whereas it works on the mb pros.

What I have found is that it is only a problem with a large amount of less files. We currently have 123 of those on which it hangs, however once I remove some, less compilation works.

I do not run out of RAM, but CPU is obviously very high - which makes sense given that sbt-less tries to parallelize as much as possible. At some point, it just stops doing anything and from what I can see in strace, it is blocked in some epoll_wait.

We have since switched to the trireme engine to work around this.

**Comment by jroper** [comment]
Interesting that switching to trireme fixes it - given that trireme is orders of magnitude slower than node.

Does it utilise high CPU for longer than you expect, or is the time that its using the high CPU expected?

It's possible that now that we're correctly reporting file dependencies, that large number of dependencies is exceeding a buffer limit somewhere when we're reporting it, and this is causing the problem.

**Comment by rethab** [comment]
I would guess that it is about as longs as I would expect it to run - though I have no exact data here. Compilation has always taken quite a long time given how many files we have.

**Comment by MariosPapasofokli** [comment]
@jroper Awesome fix, thank you
